accounting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('asset_list/', include('asset_list.urls', namespace='asset_list')),
    path('kanrihi_in/', include('kanrihi_in.urls', namespace='kanrihi_in')),
    path('kanrihi_out/', include('kanrihi_out.urls', namespace='kanrihi_out')),
    path('shuuzenhi_in/', include(
        'shuuzenhi_in.urls', namespace='shuuzenhi_in')),
    path('shuuzenhi_out/', include(
        'shuuzenhi_out.urls', namespace='shuuzenhi_out')),
    path('parking_in/', include('parking_in.urls', namespace='parking_in')),
    path('parking_out/', include('parking_out.urls', namespace='parking_out')),
    path('balance/', include('balance.urls', namespace='balance')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

balance/urls.py
from django.urls import path

from balance import views

app_name = 'balance'
urlpatterns = [
    # データ表示
    path('shuuzenhi/', views.ShuuzenhiBalanceView.as_view(), name='shuuzenhi'),
    path('check_shuuzenhi/', views.CheckShuuzenhiBalanceView.as_view(), name='check_shuuzenhi'),
    path('kanrihi/', views.KanrihiBalanceView.as_view(), name='kanrihi'),
    path('check_kanrihi/', views.CheckKanrihiBalanceView.as_view(), name='check_kanrihi'),
]

register/urls.py
from django.urls import path
from register.views import (MypageView, OperateDataView, MasterDataView,
                            OperateRepairDataView, Login, Logout)


"""
https://torina.top/detail/222/
"""
app_name = 'register'
urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('mypage', MypageView.as_view(), name='mypage'),
    path('operate_data/', OperateDataView.as_view(), name='operate_data'),
    path('operate_repair_data/', OperateRepairDataView.as_view(),
         name='operate_repair_data'),
    path('master_data/', MasterDataView.as_view(), name='master_data'),
]

shuuzenhi_in/urls.py
from django.urls import path

from shuuzenhi_in import views

app_name = 'shuuzenhi_in'
urlpatterns = [
    # データ表示
    path('incomelist/', views.IncomeListView.as_view(), name='incomelist'),
    path('uchiwakelist/',
         views.UchiwakeListView.as_view(), name='uchiwakelist'),
    # データ登録
    path('create', views.CreateIncomeView.as_view(), name='create'),
    path('create_master',
         views.CreateMasterView.as_view(), name='create_master'),
    # データ修正
    path('update_list/', views.DatalistView.as_view(), name='update_list'),
    path('update_master/<int:pk>/',
         views.UpdateMasterView.as_view(), name='update_master'),
    path('update/<int:pk>/', views.UpdateIncomeView.as_view(), name='update'),
#    # CSVデータExport
#    path('export/', views.shuuzenhi_in_export, name='export'),
]

shuuzenhi_in/models.py
from django.db import models


class Category_shuuzenhi_income(models.Model):
    """ 2021-03-10追加 """
    code = models.IntegerField()
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Master_shuuzenhi_income(models.Model):
    """ 修繕費収入の項目を定義。 """
    code = models.IntegerField()
    name = models.CharField(max_length=256)
    category = models.ForeignKey(Category_shuuzenhi_income, on_delete=models.PROTECT, null=True)
    alive = models.BooleanField(default=True, null=True, blank=True)

    def __str__(self):
        return self.name
    """
    https://stackoverflow.com/questions/9297422/get-or-create-failure-with-django-and-postgres-duplicate-key-value-violates-uni
    postgrSQL,MySQLの場合、csvファイルからの読み込みでは以下の設定が必要のようだ。
    class Meta:
        select_on_save = True
        unique_together = ('code', 'name')
    """


class Shuuzenhi_income(models.Model):
    ki = models.IntegerField()
    master = models.ForeignKey(Master_shuuzenhi_income, on_delete=models.PROTECT)
    income = models.BigIntegerField()
    comment = models.TextField(null=True, blank=True)

    def __int__(self):
        return self.income

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["ki", "master"],
                name="shuuzenhi_in_unique"
            ),
        ]

shuuzenhi_in/forms.py
from django import forms
from django.db.models.aggregates import Max

from shuuzenhi_in.models import Master_shuuzenhi_income, Shuuzenhi_income
import logging


class Shuuzenhi_incomeForm(forms.ModelForm):
    """ models.pyのモデルを追加するためModelFormとする
    https://qiita.com/felyce/items/5042db0792c9f7d01c1e
    """
    max_ki = Shuuzenhi_income.objects.aggregate(ki=Max('ki'))
    if max_ki["ki"] is None:
        ki = forms.IntegerField(label='期', initial=0)
    else:
        ki = forms.IntegerField(label='期', initial=max_ki["ki"]+1)

    master = forms.ModelChoiceField(
        queryset=Master_shuuzenhi_income.objects.all(),
        label='収入種別'
    )
    income = forms.IntegerField(label='収入額')
    comment = forms.CharField(label='コメント', widget=forms.Textarea, required=False)

    def clean_master(self):
        """ validation """
        mn = self.cleaned_data['master']
        if mn.name == '駐車場収入':
            raise forms.ValidationError("駐車場収入は駐車場会計で処理してください")
        elif mn.name == '管理会計より繰入':
            raise forms.ValidationError("管理会計からの収入は管理会計で処理してください")
        return mn
    """
    # 重複登録をチェックする。
    def clean(self):
        cleaned_data = super().clean()
        ki = cleaned_data['ki']
        master = cleaned_data['master']
        data = Shuuzenhi_income.objects.filter(ki=ki, master=master)
        if data:
            raise forms.ValidationError("既に登録済みです。")
        return cleaned_data
    """

    class Meta:
        model = Shuuzenhi_income
        fields = ("ki", "master", "income", "comment")

    def __init__(self, *args, **kwargs):
        """ フォームフィールドのwidgetを設定 """
        super().__init__(*args, **kwargs)
        self.fields['ki'].widget.attrs["class"] = "input"
        self.fields['master'].widget.attrs["class"] = "select-css"
        self.fields['income'].widget.attrs["class"] = "input"
        self.fields['comment'].widget.attrs["class"] = "textarea"
        self.fields['comment'].widget.attrs["rows"] = "4"


class Shuuzenhi_masterForm(forms.ModelForm):
    """ 修繕費収入項目マスター """
    code = forms.IntegerField(label="コード")
    name = forms.CharField(label="収入項目名", max_length=256)
    alive = forms.BooleanField(label='有効', initial=True)

    class Meta:
        model = Master_shuuzenhi_income
        fields = ("code", "name", "alive")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['code'].widget.attrs["class"] = "input is-size-6"
        self.fields['name'].widget.attrs["class"] = "input is-size-6"
        self.fields['alive'].widget.attrs["class"] = "checkbox is-size-6"

shuuzenhi_in/views.py
# import logging
from django.contrib import messages  # メッセージフレームワーク
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.db.models.aggregates import Case, Sum, When
from django.shortcuts import reverse
from django.views import generic

from shuuzenhi_in.forms import Shuuzenhi_incomeForm, Shuuzenhi_masterForm
from shuuzenhi_in.models import Master_shuuzenhi_income, Shuuzenhi_income


class IncomeListView(LoginRequiredMixin, generic.TemplateView):
    """ 修繕費収入履歴 """
    model = Shuuzenhi_income
    template_name = "shuuzenhi_in/income_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # user_id = self.request.user.id
        a = Shuuzenhi_income.objects.select_related().order_by('ki')
        context['incomelist'] = a.values('ki').annotate(
            zenki=Sum(Case(When(master__category__code=10, then='income'), default=0)),
            shuuzenhi=Sum(Case(When(master__category__code=20, then='income'), default=0)),
            parking=Sum(Case(When(master__category__code=50, then='income'), default=0)),
            kuriire=Sum(Case(When(master__category__code=60, then='income'), default=0)),
            usage=Sum(Case(When(master__category__code=30, then='income'), default=0)),
            sonota=Sum(Case(When(master__category__code=40, then='income'), default=0)),
            total=Sum(Case(When(master__category__code__gt=10, then='income'), default=0)),
        )
        return context


class UchiwakeListView(LoginRequiredMixin, generic.TemplateView):
    """ その他収入内訳リスト表示 """
    model = Shuuzenhi_income
    template_name = "shuuzenhi_in/uchiwake_list.html"

    def get_context_data(self, **kwargs):
        # はじめに継承元のメソッドを呼び出す．（おまじない）
        context = super().get_context_data(**kwargs)
        # user_id = self.request.user.id
        # sql文を生成する。
        a = Shuuzenhi_income.objects.select_related().order_by('ki')
        context['sonotalist'] = a.values('ki').annotate(
            niwa=Sum(Case(When(master__code=25, then='income'), default=0)),
            bike=Sum(Case(When(master__code=30, then='income'), default=0)),
            motor_bike=Sum(Case(When(master__code=35, then='income'), default=0)),
            risoku=Sum(Case(When(master__code=40, then='income'), default=0)),
            zatu=Sum(Case(When(master__code=60, then='income'), default=0)),
            haitou=Sum(Case(When(master__code=80, then='income'), default=0)),
        )
        return context


class CreateIncomeView(PermissionRequiredMixin, generic.CreateView):
    """ 修繕費収入データの登録
    何かの役に立つかも知れないform_valid()に関する情報。
    http://k-mawa.hateblo.jp/entry/2017/10/20/181711
    """
    model = Shuuzenhi_income
    form_class = Shuuzenhi_incomeForm
    template_name = "shuuzenhi_in/shuuzenhi_income_form.html"
    # 必要な権限
    permission_required = ("asset_list.add_assetlist")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl。プロパティ(seccess_url)を使うか、関数をオーバーライド。
    def get_success_url(self):
        return reverse('shuuzenhi_in:create')

    def form_valid(self, form):
        """ 駐車場収入は駐車場会計で処理する """
        messages.success(self.request, "保存しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "保存できませんでした。")
        return super().form_invalid(form)


class UpdateIncomeView(PermissionRequiredMixin, generic.UpdateView):
    """ 修繕費収入データを修正する """
    model = Shuuzenhi_income
    form_class = Shuuzenhi_incomeForm
    template_name = "shuuzenhi_in/shuuzenhi_income_form.html"
    # 必要な権限（データ登録できる権限は共通）
    permission_required = ("asset_list.add_assetlist")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('shuuzenhi_in:update_list')

    def form_valid(self, form):
        """ 駐車場収入は駐車場会計で処理する """
        shuuzenhi_data = form.save(commit=False)
        ki = form.cleaned_data['ki']
        master = form.cleaned_data['master']
        if master.name != '駐車場収入':
            shuuzenhi_data.save()
            msg = f'第{ki}期の{master}をアップデートしました'
        else:
            msg = '駐車場収入は駐車場会計で処理してください'

        messages.info(self.request, msg)
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "保存できませんでした。")
        return super().form_invalid(form)


class CreateMasterView(PermissionRequiredMixin, generic.CreateView):
    """ 修繕費収入項目マスターを作成する """
    model = Master_shuuzenhi_income
    form_class = Shuuzenhi_masterForm
    template_name = "shuuzenhi_in/master_shuuzenhi_income_form.html"

    # 必要な権限
    permission_required = ("admin.add_logentry")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl。プロパティ(seccess_url)を使うか、関数をオーバーライド。
    def get_success_url(self):
        return reverse('shuuzenhi_in:create_master')

    # マスターデータを表示させるため、get_context_dataをオーバーライド。
    # get_queryset()を上書きしてもよいが、templateに渡すデフォルトの変数を覚えるのが
    # 面倒なため、contextで変数名を自分で設定。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Master_shuuzenhi_income.objects.all().order_by("code")
        return context


class UpdateMasterView(PermissionRequiredMixin, generic.UpdateView):
    """ 修繕費収入項目マスターを修正する """
    model = Master_shuuzenhi_income
    form_class = Shuuzenhi_masterForm
    template_name = "shuuzenhi_in/master_shuuzenhi_income_form.html"
    permission_required = ("admin.add_logentry")

    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('shuuzenhi_in:create_master')

    # マスターデータを表示させるため、get_context_dataをオーバーライド。
    # get_queryset()を上書きしてもよいが、templateに渡すデフォルトの変数を覚えるのが
    # 面倒なため、contextで変数名を自分で設定。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Master_shuuzenhi_income.objects.all().order_by("code")
        return context


class DatalistView(PermissionRequiredMixin, generic.ListView):
    """ 修繕費収入データ修正用listを表示
    https://docs.djangoproject.com/ja/2.0/topics/pagination/
    http://thinkami.hatenablog.com/entry/2016/02/04/231901
    """
    model = Shuuzenhi_income
    template_name = 'shuuzenhi_in/update_list.html'
    # 必要な権限
    permission_required = ("asset_list.add_assetlist")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    ordering = ['-ki']
    paginate_by = 50

shuuzenhi_in/templates/shuuzenhi_in/income_list.html
{% extends "base.html" %}
{% load humanize %} {# 3桁区切りのため追加 #}
{% load static %} {# {% static  を使うため必要 #}

{% block title %}
修繕費収入履歴
{% endblock title %}

{% block head %}
{# javascriptファイルを取り込む #}
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js"></script>
<script src="{% static 'shuuzenhi_in/shuuzenhi_in_chart.js' %}"></script>
{% endblock head %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'register:mypage' %}">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a href="{% url 'shuuzenhi_in:uchiwakelist' %}" class="navbar-item">使用料＋その他</a>
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:mypage' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
<div class="container is-fluid">
  <div class="content has-text-centered">
    <h4>修繕会計収入履歴</h4>
  </div>
  <div class="content table-container">
    <table class="table is-narrow is-striped is-responsible">
      <thead>
        <tr>
          <th class="has-text-centered">期</th>
          <th class="has-text-centered">前期繰越</th>
          <th class="has-text-centered">修繕積立金</th>
          <th class="has-text-centered">使用料</th>
          <th class="has-text-centered">その他</th>
          <th class="has-text-centered">管理会計より</th>
          <th class="has-text-centered">駐車場会計より</th>
          <th class="has-text-centered">合計</th>
        </tr>
      </thead>
      <tbody>
        {% for data in incomelist %}
        <tr>
          <td class="has-text-centered">{{ data.ki }}</td>
          <td class="has-text-right">{{ data.zenki|intcomma}}</td>
          <td class="has-text-right">{{ data.shuuzenhi|intcomma}}</td>
          <td class="has-text-right">{{ data.usage|intcomma}}</td>
          <td class="has-text-right">{{ data.sonota|intcomma }}</td>
          <td class="has-text-right">{{ data.kuriire|intcomma }}</td>
          <td class="has-text-right">{{ data.parking|intcomma }}</td>
          <td class="has-text-right">{{ data.total|intcomma }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <br>
  {# グラフ表示エリア #}
  <div class="md_container">
    <canvas id="stage" width="300" height="200"></canvas>
  </div>
  
  {# 以下でグラフ作成用のデータを生成する． templateで処理を書いて良いものだろうか？ #}
  <script type="text/javascript">
    var data = [];
  </script>
  {% for income in incomelist %}
  <script type="text/javascript">
    var list = [];
    list.push("{{income.ki}}");
    list.push("{{income.zenki}}");
    list.push("{{income.shuuzenhi}}");
    list.push("{{income.kuriire}}");
    list.push("{{income.parking}}");
    list.push("{{income.total}}");
    data.push(list);
  </script>
  {% endfor %}
  <script type="text/javascript">
    //console.log(data);
    incomeShuuzenhiChart(data);
  </script>
  <br>
  <hr>
  {% endblock %}
</div>

shuuzenhi_in/templates/shuuzenhi_in/master_shuuzenhi_income_form.html
{# https://stackoverflow.com/questions/39123348/how-to-pass-a-queryset-from-django-to-javascript-function #}
{% extends "base.html" %}

{% block title %}
修繕費収入項目の登録/修正
{% endblock title %}

{% block navbar %}
<nav class="navbar is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:master_data' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container">
  <div class="content has-text-centered">
    <h4>修繕費収入項目マスターの登録/修正</h4>
  </div>
  <form method='POST' enctype='multipart/form-data' id='form_style'>
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class='field'>
        <div class='control'>
          <div class='label'>{{ field.label_tag }}</div>
          <div class='my_field'>{{ field }}</div>
          {% if field.help_text %}
            <span class='helptext'>{{ field.help_text }}</span>
          {% endif %}
          {{ field.errors }}
        </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <br>
    <div class='content has-text-centered my_button'>
      <button type='submit' class='button is-primary'>読込み</button>
      <a class='button is-danger' href='javascript:void(0);' onclick='window.history.back();'>キャンセル</a>
    </div>
  </form>
  <hr>
  <table class="table is-narrow" >
    <thead>
      <tr>
        <th class="text-center">コード</th>
        <th class="text-center">項目名</th>
        <th class="text-center">修正</th>
      </tr>
    </thead>
    <tbody>
      {% for list in masterlist %}
      <tr>
        <td class="text-center">{{ list.code }}</td>
        <td class="text-left">{{ list.name }}</td>
        <td class="text-center"><a href="{% url 'shuuzenhi_in:update_master' list.id %}">修正</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

shuuzenhi_in/templates/shuuzenhi_in/shuuzenhi_income_form.html
{# https://stackoverflow.com/questions/39123348/how-to-pass-a-queryset-from-django-to-javascript-function #}
{% extends "base.html" %}

{% block title %}
修繕費収入データの登録
{% endblock title %}

{% block navbar %}
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:operate_data' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
<div class="container">
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  <div class="content has-text-centered">
    <h4>修繕費収入データの登録</h4>
  </div>
  <form method='POST' enctype='multipart/form-data' id='form_style'>
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class='field'>
        <div class='control'>
          <div class='label'>{{ field.label_tag }}</div>
          <div class='my_field'>{{ field }}</div>
          {% if field.help_text %}
            <span class='helptext'>{{ field.help_text }}</span>
          {% endif %}
          {{ field.errors }}
        </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <br>
    <div class='my_button has-text-centered'>
      <button type='submit' class='button is-primary'>読込み</button>
      <a class='button is-danger' href='javascript:void(0);' onclick='window.history.back();'>キャンセル</a>
    </div>
  </form>
</div>
{% endblock content %}

shuuzenhi_in/templates/shuuzenhi_in/uchiwake_list.html
{% extends "base.html" %}
{% load humanize %} {# 3桁区切りのため追加 #}
{% load static %} {# {% static  を使うため必要 #}

{% block title %}
その他収入
{% endblock title %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'register:mypage' %}">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a href="{% url 'shuuzenhi_in:incomelist' %}" class="navbar-item">収入履歴</a>
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:mypage' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
<div class="container">
  <div class="content has-text-centered">
    <h4>使用料＋その他</h4>
  </div>
  <br>
  <div class="content table-container">
    <table class="table is-striped is-narrow is-responsible">
      <thead>
        <tr>
          <th class="has-text-centered">期</th>
          <th class="has-text-centered">専用庭</th>
          <th class="has-text-centered">駐輪場</th>
          <th class="has-text-centered">バイク置場</th>
          <th class="has-text-centered">利息収入</th>
          <th class="has-text-centered">雑収入</th>
          <th class="has-text-centered">配当金</th>
          <th class="has-text-centered">合計</th>
        </tr>
      </thead>
      <tbody>
        {% for u in sonotalist %}
        <tr>
          <td class="has-text-centered">{{ u.ki }} </td>
          <td class="has-text-right">{{ u.niwa|intcomma}}</td>
          <td class="has-text-right">{{ u.bike|intcomma}}</td>
          <td class="has-text-right">{{ u.motor_bike|intcomma}}</td>
          <td class="has-text-right">{{ u.risoku|intcomma}}</td>
          <td class="has-text-right">{{ u.zatu|intcomma}}</td>
          <td class="has-text-right">{{ u.haitou|intcomma}}</td>
          <td class="has-text-right">{{ u.niwa|add:u.bike|add:u.motor_bike|add:u.risoku|add:u.zatu|add:u.haitou|intcomma}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

shuuzenhi_in/templates/shuuzenhi_in/update_list.html
{# https://stackoverflow.com/questions/39123348/how-to-pass-a-queryset-from-django-to-javascript-function #}
{% extends "base.html" %}
{% load humanize %} {# 3桁区切りのため追加 #}

{% block title %}
修繕費収入データの修正
{% endblock title %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'register:mypage' %}">【SG川崎】</a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:operate_data' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}
<br>
<div class="container">
  {% if messages %}
  <div class="container" style="margin-top:1rem;">
    <div class="notification is-info">
      <button class="delete" type="button"></button>
        {% for message in messages %}
        <p> {{ message }}</p>
        {% endfor %}
    </div>
  </div>
  {% endif %}

  <div class="content has-text-centered">
    <h4>修繕費収入データの修正</h4>
  </div>
  <div class="content table-container">
    <table class="table is-narrow is-striped">
      <thead>
        <tr>
          <th class="has-text-centered">ki</th>
          <th class="has-text-centered">master_id</th>
          <th class="has-text-centered">income</th>
          <th class="has-text-centered">修正</th>
        </tr>
      </thead>
      <tbody>
        {% for list in shuuzenhi_income_list %}
        <tr>
          <td class="has-text-centered">{{ list.ki }}</td>
          <td class="has-text-left">{{ list.master }}</td>
          <td class="has-text-right">{{ list.income|intcomma }}</td>
          <td class="has-text-centered">
            <a href="{% url 'shuuzenhi_in:update' list.id %}">
              修正
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {# http://thinkami.hatenablog.com/entry/2016/02/04/231901 #}
  {% include 'page.html' %}
  <br>
</div>

{% endblock content %}