accounting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('asset_list/', include('asset_list.urls', namespace='asset_list')),
    path('kanrihi_in/', include('kanrihi_in.urls', namespace='kanrihi_in')),
    path('kanrihi_out/', include('kanrihi_out.urls', namespace='kanrihi_out')),
    path('shuuzenhi_in/', include(
        'shuuzenhi_in.urls', namespace='shuuzenhi_in')),
    path('shuuzenhi_out/', include(
        'shuuzenhi_out.urls', namespace='shuuzenhi_out')),
    path('parking_in/', include('parking_in.urls', namespace='parking_in')),
    path('parking_out/', include('parking_out.urls', namespace='parking_out')),
    path('balance/', include('balance.urls', namespace='balance')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

balance/urls.py
from django.urls import path

from balance import views

app_name = 'balance'
urlpatterns = [
    # データ表示
    path('shuuzenhi/', views.ShuuzenhiBalanceView.as_view(), name='shuuzenhi'),
    path('check_shuuzenhi/', views.CheckShuuzenhiBalanceView.as_view(), name='check_shuuzenhi'),
    path('kanrihi/', views.KanrihiBalanceView.as_view(), name='kanrihi'),
    path('check_kanrihi/', views.CheckKanrihiBalanceView.as_view(), name='check_kanrihi'),
]

kanrihi_in/urls.py
from django.urls import path
from kanrihi_in import views

app_name = 'kanrihi_in'
urlpatterns = [
    # データ表示
    path('incomelist/',
         views.IncomeListView.as_view(), name='incomelist'),
    path('uchiwakelist/',
         views.UchiwakeListView.as_view(), name='uchiwakelist'),
    # データ登録
    path('create_income',
         views.CreateIncomeView.as_view(), name='create_income'),
    path('create_master',
         views.CreateMasterView.as_view(), name='create_master'),
    # 修正のための一覧表
    path('update_list/',
         views.UpdateIncomelistView.as_view(), name='update_list'),
    path('update/<int:pk>/',
         views.UpdateIncomeView.as_view(), name='update'),
    path('update_master/<int:pk>/',
         views.UpdateMasterView.as_view(), name='update_master'),
    path('create_category',
         views.CreateCategoryView.as_view(), name='create_category'),
    path('update_category/<int:pk>/',
         views.UpdateCategoryView.as_view(), name='update_category'),
#    # CSVデータExport
#    path('export/', views.kanrihi_in_export, name='export'),
]

register/urls.py
from django.urls import path
from register.views import (MypageView, OperateDataView, MasterDataView,
                            OperateRepairDataView, Login, Logout)


"""
https://torina.top/detail/222/
"""
app_name = 'register'
urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('mypage', MypageView.as_view(), name='mypage'),
    path('operate_data/', OperateDataView.as_view(), name='operate_data'),
    path('operate_repair_data/', OperateRepairDataView.as_view(),
         name='operate_repair_data'),
    path('master_data/', MasterDataView.as_view(), name='master_data'),
]

kanrihi_in/models.py
from django.db import models


class Category_income(models.Model):
    """ 2019-01-06追加 """
    code = models.IntegerField()
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Master_kanrihi_income(models.Model):
    """ 管理費収入の項目を定義 """
    code = models.IntegerField()
    name = models.CharField(max_length=256)
    category = models.ForeignKey(Category_income, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.name


class Kanrihi_income(models.Model):
    ki = models.IntegerField()
    master = models.ForeignKey(Master_kanrihi_income, on_delete=models.PROTECT, null=True)
    income = models.BigIntegerField()
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.master.name

    class Meta:
        """ ユニーク制約の設定
        https://docs.djangoproject.com/en/3.1/ref/models/options/#django.db.models.Options.unique_together
        """
        constraints = [
            models.UniqueConstraint(
                fields=["ki", "master"],
                name="kanrihi_in_unique"
            ),
        ]

kanrihi_in/forms.py
# import logging
from datetime import datetime

from django import forms
from django.conf import settings

# from django.db.models.aggregates import Max
from kanrihi_in.models import (Category_income, Kanrihi_income,
                               Master_kanrihi_income)


class Kanrihi_incomeForm(forms.ModelForm):
    """ models.pyのモデルを追加するためModelFormとする
    https://qiita.com/felyce/items/5042db0792c9f7d01c1e
    """
    # 新しく登録する「期」をデフォルト表示するため。
    this_ki = datetime.now().year - settings.START_YEAR - 1
    ki = forms.IntegerField(label='期', initial=this_ki)
    # 以下はtemplatesでformフィールド名を表示させるため。無くても表示がmodelsの要素名になるだけ。
    master = forms.ModelChoiceField(
        queryset=Master_kanrihi_income.objects.all(),
        label='収入種別'
    )
    income = forms.IntegerField(label='収入額')

    def clean_master(self):
        """ validation """
        mn = self.cleaned_data['master']
        if mn.name == '駐車場収入':
            raise forms.ValidationError("駐車場収入は駐車場会計で処理してください")
        return mn

    class Meta:
        model = Kanrihi_income
        fields = ("ki", "master", "income")

    # fieldにbulma用のclassを設定する。
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ki'].widget.attrs["class"] = "input"
        self.fields['master'].widget.attrs["class"] = "select-css"
        self.fields['income'].widget.attrs["class"] = "input"
        """
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
        """


class Kanrihi_masterForm(forms.ModelForm):
    """ 管理費収入項目マスター作成用Form """
    code = forms.IntegerField(label="コード")
    name = forms.CharField(label="収入項目名", max_length=256)

    class Meta:
        model = Master_kanrihi_income
        fields = ("code", "name", "category")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['code'].widget.attrs["class"] = "input is-size-6"
        self.fields['name'].widget.attrs["class"] = "input is-size-6"
        self.fields['category'].widget.attrs["class"] = "select-css is-size-6"


class Master_categoryForm(forms.ModelForm):
    """ 管理費収入カテゴリーの登録用フォーム """
    name = forms.CharField(
        label="収入カテゴリ名",
        max_length=256,
        widget=forms.TextInput(attrs={'class': 'input is-size-6'})
        )

    class Meta:
        model = Category_income
        fields = ("code", "name",)

    # fieldにclassを設定する。
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['code'].widget.attrs["class"] = "input is-size-6"

kanrihi_in/views.py
# import logging
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.db.models.aggregates import Case, Sum, When
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views import generic

from kanrihi_in.forms import Kanrihi_incomeForm, Kanrihi_masterForm, Master_categoryForm
from kanrihi_in.models import Kanrihi_income, Master_kanrihi_income, Category_income


class IncomeListView(LoginRequiredMixin, generic.TemplateView):
    """ 管理費収入リスト表示 """
    model = Kanrihi_income
    template_name = "kanrihi_in/income_list.html"  # template名の指定は必須．

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # user_id = self.request.user.id
        # sql文を生成する。
        """
        行の集約：values().annotate()の順番で記述する．
        values()：集約キー
        annotate()：下記を参照
        """
        a = Kanrihi_income.objects.select_related().order_by('ki')
        a = a.values('ki').annotate(
            zenki_kurikosi=Sum(Case(When(master__category__code=10, then='income'), default=0)),
            kanrihi=Sum(
                Case(When(master__category__code=20, then='income'), default=0)),
            sonota=Sum(
                Case(When(master__category__code=30, then='income'), default=0)),
            parking=Sum(
                Case(When(master__category__code=40, then='income'), default=0)),
            total=Sum('income'),
        )
        context['incomelist'] = a
        return context


class UchiwakeListView(LoginRequiredMixin, generic.TemplateView):
    """ その他収入内訳リスト表示 """
    model = Kanrihi_income
    template_name = "kanrihi_in/uchiwake_list.html"  # template名の指定は必須．

    def get_context_data(self, **kwargs):
        # はじめに継承元のメソッドを呼び出す．（おまじない）
        context = super().get_context_data(**kwargs)
        # user_id = self.request.user.id
        # sql文を生成する。
        a = Kanrihi_income.objects.select_related().order_by('ki')
        context['sonotalist'] = a.values('ki').annotate(
            niwa=Sum(Case(When(master__code=40, then='income'), default=0)),
            bike=Sum(Case(When(master__code=50, then='income'), default=0)),
            ryokuchi=Sum(
                Case(When(master__code=60, then='income'), default=0)),
            risoku=Sum(Case(When(master__code=70, then='income'), default=0)),
            zatu=Sum(Case(When(master__code=80, then='income'), default=0)),
            hoken=Sum(Case(When(master__code=90, then='income'), default=0)),
            total=Sum(Case(When(master__category__code=30, then='income'), default=0)),
        )
        return context


class CreateIncomeView(PermissionRequiredMixin, generic.CreateView):
    """ 管理費収入データを登録する """
    model = Kanrihi_income
    form_class = Kanrihi_incomeForm
    template_name = "kanrihi_in/kanrihi_income_form.html"
    # 必要な権限
    permission_required = ("asset_list.add_assetlist")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    # 保存が成功した場合に遷移するurl
    success_url = reverse_lazy('kanrihi_in:create_income')

    def form_valid(self, form):
        """ 駐車場収入は駐車場会計で処理する """
        return super().form_valid(form)


class UpdateIncomelistView(PermissionRequiredMixin, generic.ListView):
    """ 修正するデータを選択するための一覧表を表示
        https://docs.djangoproject.com/ja/2.0/topics/pagination/
        http://thinkami.hatenablog.com/entry/2016/02/04/231901
    """
    model = Kanrihi_income
    template_name = 'kanrihi_in/update_list.html'
    # 必要な権限
    permission_required = ("asset_list.add_assetlist")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    ordering = ['-ki']
    paginate_by = 40


class UpdateIncomeView(PermissionRequiredMixin, generic.UpdateView):
    """ 管理費収入データを修正する """
    model = Kanrihi_income
    form_class = Kanrihi_incomeForm
    template_name = "kanrihi_in/kanrihi_income_form.html"
    # 必要な権限
    permission_required = ("asset_list.add_assetlist")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True
    # 保存が成功した場合に遷移するurl
    success_url = reverse_lazy('kanrihi_in:update_list')

    def form_valid(self, form):
        """ 駐車場収入は駐車場会計で処理する """
        messages.success(self.request, "保存しました。")
        return super().form_valid(form)


class CreateMasterView(PermissionRequiredMixin, generic.CreateView):
    """ 管理費マスターデータを登録する """
    model = Master_kanrihi_income
    form_class = Kanrihi_masterForm
    template_name = "kanrihi_in/master_income_form.html"
    permission_required = ("admin.add_logentry")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # マスターデータを表示させるため、get_context_dataをオーバーライド。
    # get_queryset()を上書きしてもよいが、templateに渡すデフォルトの変数を覚えるのが
    # 面倒なため、contextで変数名を自分で設定。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Master_kanrihi_income.objects.all()
        return context

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('kanrihi_in:create_master')

    # データvalidationが成功したら、メッセージを表示させる。
    def form_valid(self, form):
        messages.success(self.request, "保存しました。")
        return super().form_valid(form)

    # def form_invalid(self, form):
    #     messages.warning(self.request, "保存できませんでした。")
    #     return super().form_invalid(form)


class UpdateMasterView(PermissionRequiredMixin, generic.UpdateView):
    """ 管理費収入項目マスターを修正する """
    model = Master_kanrihi_income
    form_class = Kanrihi_masterForm
    template_name = "kanrihi_in/master_income_form.html"
    permission_required = ("admin.add_logentry")

    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('kanrihi_in:create_master')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Master_kanrihi_income.objects.all()
        return context


class CreateCategoryView(PermissionRequiredMixin, generic.CreateView):
    """ 管理費収入カテゴリーを登録する """
    model = Category_income
    form_class = Master_categoryForm
    template_name = "kanrihi_in/category_form.html"
    # 必要な権限
    permission_required = ("admin.add_logentry")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('kanrihi_in:create_category')

    # データvalidationが成功したら、メッセージを表示させる。
    def form_valid(self, form):
        messages.success(self.request, "保存しました。")
        return super().form_valid(form)

    # def form_invalid(self, form):
    #     messages.warning(self.request, "保存できませんでした。")
    #     return super().form_invalid(form)

    # マスターデータを表示させるため、get_context_dataをオーバーライド。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Category_income.objects.all().order_by('code')
        return context


class UpdateCategoryView(PermissionRequiredMixin, generic.UpdateView):
    """ 管理費支出カテゴリーを修正する """
    model = Category_income
    form_class = Master_categoryForm
    template_name = "kanrihi_in/category_form.html"
    # 必要な権限
    permission_required = ("admin.add_logentry")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('kanrihi_in:create_category')

    # マスターデータを表示させるため、get_context_dataをオーバーライド。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Category_income.objects.all()
        return context

kanrihi_in/templates/kanrihi_in/category_form.html
{% extends "base.html" %}

{% block title %}
管理費収入カテゴリーの登録
{% endblock title %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:master_data' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container">
  <div class="content has-text-centered">
    <h4>管理費収入カテゴリーの登録/修正</h4>
  </div>
  <form method='POST' enctype='multipart/form-data' id='form_style'>
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class='field'>
        <div class='control'>
          <div class='label'>{{ field.label_tag }}</div>
          <div class='my_field'>{{ field }}</div>
          {% if field.help_text %}
            <span class='helptext'>{{ field.help_text }}</span>
          {% endif %}
          {{ field.errors }}
        </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <br>
    <div class='content has-text-centered my_button'>
      <button type='submit' class='button is-primary'>読込み</button>
      <a class='button is-danger' href='javascript:void(0);' onclick='window.history.back();'>キャンセル</a>
    </div>
  </form>

  <br>
  <hr>
  <table class="table is-narrow" >
    {# 行高 table-md #}
    <thead>
      <tr>
        <th class="has-text-centered">コード</th>
        <th class="has-text-centered">カテゴリー名</th>
        <th class="has-text-centered">修正</th>
      </tr>
    </thead>
    <tbody>
      {% for list in masterlist %}
      <tr>
        <td class="has-text-centered">{{ list.code }}</td>
        <td class="has-text-left">{{ list.name }}</td>
        <td class="has-text-centered"><a href="{% url 'kanrihi_in:update_category' list.id %}">修正</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

kanrihi_in/templates/kanrihi_in/income_list.html
{% extends "base.html" %}
{% load humanize %} {# 3桁区切りのため追加 #}
{% load static %} {# {% static  を使うため必要 #}

{% block title %}
管理費収入履歴
{% endblock title %}

{% block head %}
{# javascriptファイルを取り込む #}
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js"></script>
<script src="{% static 'kanrihi_in/kanrihi_in_chart.js' %}"></script>
{% endblock head %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'register:mypage' %}">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a href="{% url 'kanrihi_in:uchiwakelist' %}" class="navbar-item">その他内訳</a>
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:mypage' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
<div class="container">
  <div class="content has-text-centered">
    <h4>管理費収入履歴</h4>
  </div>
  <br>
  {% comment %} <div class="content table-container"> {% endcomment %}
  <div class="content table-container">
    <table class="table is-narrow is-striped">
      <thead>
        <tr>
          <th class="has-text-centered">期</th>
          <th class="has-text-centered">西暦</th>
          <th class="has-text-centered">前期繰越</th>
          <th class="has-text-centered">定額管理費</th>
          <th class="has-text-centered">その他収入</th>
          <th class="has-text-centered">駐車場会計より</th>
          <th class="has-text-centered">収入合計</th>
        </tr>
      </thead>
      <tbody>
        {% for income in incomelist %}
        <tr>
          <td class="has-text-centered">{{ income.ki }}</td>
          <td class="has-text-centered nowrap">{{income.ki|add:1998}}</td>
          <td class="has-text-right nowrap">{{ income.zenki_kurikosi|intcomma}}</td>
          <td class="has-text-right nowrap">{{ income.kanrihi|intcomma}}</td>
          <td class="has-text-right nowrap">{{ income.sonota|intcomma }}</td>
          <td class="has-text-right nowrap">{{ income.parking|intcomma }}</td>
          <td class="has-text-right nowrap">{{ income.total|intcomma }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{# グラフ表示エリア #}
{# https://misc.0o0o.org/chartjs-doc-ja/general/responsive.html #}
{#<div class="mx-auto" style="position: relative; width:90%" >#}
{#    <canvas id="stage" width="300" height="200"></canvas>#}
{#</div>#}
{#<div class="mx-auto" style="width: 800px;">#}
{#    <canvas id="stage" width="800" height="480"></canvas>#}
{#</div>#}
{# https://obel.hatenablog.jp/entry/20160626/1466937585 #}

<div class="md_container">
  <canvas id="stage" width="300" height="200"></canvas>
</div>

{# 以下でグラフ作成用のデータを生成する． templateで処理を書いて良いものだろうか？ #}
<script type="text/javascript">
  var data = [];
</script>
{% for income in incomelist %}
<script type="text/javascript">
  var list = [];
  list.push("{{income.ki}}");
  list.push("{{income.kanrihi}}");
  list.push("{{income.zenki_kurikosi}}");
  list.push("{{income.sonota}}");
  list.push("{{income.parking}}");
  data.push(list);
</script>
{% endfor %}
<script type="text/javascript">
  //console.log(data);
  incomeKanrihiChart(data);
</script>
<br>
<hr>
{% endblock %}
</div>

kanrihi_in/templates/kanrihi_in/master_income_form.html
{# https://stackoverflow.com/questions/39123348/how-to-pass-a-queryset-from-django-to-javascript-function #}
{% extends "base.html" %}

{% block title %}
管理費収入項目マスターの登録/修正
{% endblock title %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:master_data' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container">
  <div class="content has-text-centered">
    <h4>管理費収入項目マスターの登録/修正</h4>
  </div>
  <form method='POST' enctype='multipart/form-data' id='form_style'>
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class='field'>
        <div class='control'>
          <div class='label'>{{ field.label_tag }}</div>
          <div class='my_field'>{{ field }}</div>
          {% if field.help_text %}
            <span class='helptext'>{{ field.help_text }}</span>
          {% endif %}
          {{ field.errors }}
        </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <br>
    <div class='content has-text-centered my_button'>
      <button type='submit' class='button is-primary'>読込み</button>
      <a class='button is-danger' href='javascript:void(0);' onclick='window.history.back();'>キャンセル</a>
    </div>
  </form>
</div>
<hr>
<div class="container">
  <table class="table is-narrow" >
    <thead>
      <tr>
        <th class="has-text-centered">コード</th>
        <th class="has-text-centered">項目名</th>
        <th class="has-text-centered">カテゴリー</th>
        <th class="has-text-centered">修正</th>
      </tr>
    </thead>
    <tbody>
      {% for list in masterlist %}
      <tr>
        <td class="has-text-centered">{{ list.code }}</td>
        <td class="has-text-left">{{ list.name }}</td>
        <td class="has-text-centered">{{ list.category }}</td>
        <td class="has-text-centered"><a href="{% url 'kanrihi_in:update_master' list.id %}">修正</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br>
{% endblock content %}

kanrihi_in/templates/kanrihi_in/update_list.html
{# https://stackoverflow.com/questions/39123348/how-to-pass-a-queryset-from-django-to-javascript-function #}
{% extends "base.html" %}
{% load humanize %} {# 3桁区切りのため追加 #}

{% block title %}
管理費収入データの修正
{% endblock title %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'register:mypage' %}">【SG川崎】</a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a class="navbar-item" href="javascript:void(0);" onclick="window.history.back();">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}
<br>
{% block content %}
<div class="container has-text-centered">
  {% if messages %}
  <div class="container" style="margin-top:1rem;">
    <div class="notification is-info">
      <button class="delete" type="button"></button>
        {% for message in messages %}
        <p> {{ message }}</p>
        {% endfor %}
    </div>
  </div>
  {% endif %}
  <br>
  <div class="content">
    <h4>管理費収入データの修正</h4>
  </div>
  <table class="table is-narrow" >
    <thead>
      <tr>
        <th class="has-text-centered">期</th>
        <th class="has-text-centered">費目</th>
        <th class="has-text-centered">管理費収入金額</th>
        <th class="has-text-centered">修正</th>
      </tr>
    </thead>
    <tbody>
      {% for list in kanrihi_income_list %}
      <tr>
        <td>{{ list.ki }}</td>
        <td>{{ list.master }}</td>
        <td class="has-text-right">{{ list.income|intcomma }}</td>
        <td> <a href="{% url 'kanrihi_in:update' list.id %}">修正</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <!-- http://thinkami.hatenablog.com/entry/2016/02/04/231901 -->
  {% include 'page.html' %}
  <br>
</div>
{% endblock content %}