accounting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('asset_list/', include('asset_list.urls', namespace='asset_list')),
    path('kanrihi_in/', include('kanrihi_in.urls', namespace='kanrihi_in')),
    path('kanrihi_out/', include('kanrihi_out.urls', namespace='kanrihi_out')),
    path('shuuzenhi_in/', include(
        'shuuzenhi_in.urls', namespace='shuuzenhi_in')),
    path('shuuzenhi_out/', include(
        'shuuzenhi_out.urls', namespace='shuuzenhi_out')),
    path('parking_in/', include('parking_in.urls', namespace='parking_in')),
    path('parking_out/', include('parking_out.urls', namespace='parking_out')),
    path('balance/', include('balance.urls', namespace='balance')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

balance/urls.py
from django.urls import path

from balance import views

app_name = 'balance'
urlpatterns = [
    # データ表示
    path('shuuzenhi/', views.ShuuzenhiBalanceView.as_view(), name='shuuzenhi'),
    path('check_shuuzenhi/', views.CheckShuuzenhiBalanceView.as_view(), name='check_shuuzenhi'),
    path('kanrihi/', views.KanrihiBalanceView.as_view(), name='kanrihi'),
    path('check_kanrihi/', views.CheckKanrihiBalanceView.as_view(), name='check_kanrihi'),
]

kanrihi_in/urls.py
from django.urls import path
from kanrihi_in import views

app_name = 'kanrihi_in'
urlpatterns = [
    # データ表示
    path('incomelist/',
         views.IncomeListView.as_view(), name='incomelist'),
    path('uchiwakelist/',
         views.UchiwakeListView.as_view(), name='uchiwakelist'),
    # データ登録
    path('create_income',
         views.CreateIncomeView.as_view(), name='create_income'),
    path('create_master',
         views.CreateMasterView.as_view(), name='create_master'),
    # 修正のための一覧表
    path('update_list/',
         views.UpdateIncomelistView.as_view(), name='update_list'),
    path('update/<int:pk>/',
         views.UpdateIncomeView.as_view(), name='update'),
    path('update_master/<int:pk>/',
         views.UpdateMasterView.as_view(), name='update_master'),
    path('create_category',
         views.CreateCategoryView.as_view(), name='create_category'),
    path('update_category/<int:pk>/',
         views.UpdateCategoryView.as_view(), name='update_category'),
#    # CSVデータExport
#    path('export/', views.kanrihi_in_export, name='export'),
]

register/urls.py
from django.urls import path
from register.views import (MypageView, OperateDataView, MasterDataView,
                            OperateRepairDataView, Login, Logout)


"""
https://torina.top/detail/222/
"""
app_name = 'register'
urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('mypage', MypageView.as_view(), name='mypage'),
    path('operate_data/', OperateDataView.as_view(), name='operate_data'),
    path('operate_repair_data/', OperateRepairDataView.as_view(),
         name='operate_repair_data'),
    path('master_data/', MasterDataView.as_view(), name='master_data'),
]

shuuzenhi_out/urls.py
from django.urls import path

from shuuzenhi_out import views

app_name = 'shuuzenhi_out'
urlpatterns = [
    # データ表示
    path('rirekilist/', views.RirekiListView.as_view(), name='rirekilist'),
    path('shubetulist/',
         views.KoujiShubetuListView.as_view(), name='shubetulist'),
    path('expenselist/',
         views.ShuuzenhiExpenseListView.as_view(), name='expenselist'),
    path('expenselist/<int:sw>',
         views.ShuuzenhiExpenseListView.as_view(), name='expenselist'),
    path('detail/<int:pk>',
         views.ExpenseDetailView.as_view(), name='detail'),
    # path('quotation/',
    #     views.QuotationListView.as_view(), name='quotation'),
    # path('view_quotation/<int:pk>', views.view_quotation, name='view_quotation'),
    # データ登録
    path('create',
         views.CreateExpenseView.as_view(), name='create'),
    path('create_koujitype', views.CreateKoujiTypeView.as_view(),
         name='create_koujitype'),
    path('create_constractor', views.CreateConstractorView.as_view(),
         name='create_constractor'),
    # データ修正
    path('update_list/', views.RirekiUpdateListView.as_view(), name='update_list'),
    path('update/<int:pk>/', views.UpdateRirekiView.as_view(), name='update'),
    # path('update_accounttype/<int:pk>/',
    #     views.UpdateAccountingTypeView.as_view(), name='update_accounttype'),
    path('update_koujitype/<int:pk>/',
         views.UpdateKoujitypeView.as_view(), name='update_koujitype'),
    path('update_constractor/<int:pk>/',
         views.UpdateConstractorView.as_view(), name='update_constractor'),
    # CSVデータExport
    # path('export/', views.Export, name='export'),

    # BigCategoruに属するファイルを一覧表示
    # path('bigcategory/<int:pk>/', views.BigCategoryView.as_view(), name='bigcategory'),
]

shuuzenhi_out/models.py
# Create your models here.
from django.db import models
from django.conf import settings
from asset_list.models import AccountType


class Master_koujitype(models.Model):
    """ 修繕計画における工事区分 """
    koujitype = models.CharField(max_length=256)
    sequense = models.IntegerField()
    live = models.IntegerField(default=1)  # 0 or 1

    def __str__(self):
        return self.koujitype


class Constractor(models.Model):
    """ 施工業者 """
    sequense = models.IntegerField(default=0)
    name = models.CharField(max_length=128, unique=True)
    comment = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Shuuzenhi_expense(models.Model):
    """ 工事支出データ """
    year = models.IntegerField(default=2009)
    # month = models.IntegerField(null=True, blank=True)
    # django2ではon_deleteが無いとエラー．https://code.i-harness.com/ja/q/59f5a4
    koujitype = models.ForeignKey(Master_koujitype, on_delete=models.PROTECT, null=True)
    koujimei = models.CharField(max_length=256)
    cost = models.BigIntegerField()
    constractor = models.ForeignKey(Constractor, on_delete=models.PROTECT, null=True, blank=True)
    account_type = models.ForeignKey(AccountType, on_delete=models.PROTECT, null=True, blank=True)
    # 見積書ファイルデータのID
    quotation_id = models.IntegerField(default=0)
    comment = models.TextField(blank=True)

    def __str__(self):
        return self.koujimei

    # costの合計をpython関数で求める。
    def calc_total(self, sql):
        cost_list = sql
        total = 0
        for data in cost_list:
            total += data.cost
        return total

shuuzenhi_out/views.py
# import logging

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.db.models import F, Q
from django.db.models.aggregates import Case, Max, Sum, When
from django.http import HttpResponse
# from django.shortcuts import get_object_or_404, reverse
from django.shortcuts import reverse
from django.views import generic

# from file_storage.models import File
from shuuzenhi_out.forms import (ConstractorForm, Master_koujitypeForm,
                                 RirekiListForm, Shuuzenhi_expenseForm)
from shuuzenhi_out.models import (Constractor, Master_koujitype,
                                  Shuuzenhi_expense)


class RirekiListView(LoginRequiredMixin, generic.TemplateView):
    """ 個別工事リスト
        1. contextを返さなくてもobject_list(単数ならobject)でテンプレートから参照できる．
        2. filter()を使わなければquerysetだけでget_context_data()が必要ない．
        3. queryset = Swap.objects.all().order_by('-hiduke')
        4. TemplateViewではtemplate_nameは必要。
        http://tnakamura.hatenablog.com/entry/20111110/django_class_based_generic_view
    """
    model = Shuuzenhi_expense
    # form_classはどのような時に必要か？
    form_class = RirekiListForm
    # TemplateViewの場合はtemplate_nameは必須．
    template_name = "shuuzenhi_out/rireki_list.html"

    # テンプレートで扱うときのクエリセットの名前を指定
    # 今回はcontextで抽出オブジェクトを返しているから必要ない。
    # context_object_name = "rirekilist"
    # get_context_data の引数の kwargs には、urls.py で指定した名前つきの
    # 正規表現のプレースホルダにマッチした内容が入ってくるが、
    # この内容は self.kwargs にも入っていてアクセスできる。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_name = self.request.user
        # formのselect要素の値を得る
        kouji_type = self.request.GET.get('kouji_type', None)
        ac_type = self.request.GET.get('account_type', None)
        yyyy = Shuuzenhi_expense.objects.aggregate(year=Max('year'))['year']
        # 初期値として当年を設定。
        year = self.request.GET.get('year', yyyy)

        # ''が返された時の処理
        if kouji_type == '':
            kouji_type = None
        if ac_type == '':
            ac_type = None
        if year == '':
            year = None

        # Qオブジェクト作成
        koujitype_q = Q()
        actype_q = Q()
        year_q = Q()
        if kouji_type:
            koujitype_q = Q(koujitype=kouji_type)
        if ac_type:
            actype_q = Q(account_type=ac_type)
        if year:
            year_q = Q(year=year)
        sql = Shuuzenhi_expense.objects.filter(koujitype_q & actype_q & year_q).order_by('-year')

        # formのselectに初期値を設定する．http://i2bskn.hateblo.jp/entry/20120826/1345936779
        form = RirekiListForm(
            initial={'kouji_type': kouji_type, 'account_type': ac_type, 'year': year})

        # コストの合計を計算する
        total = Shuuzenhi_expense.calc_total(self, sql)
        context["total"] = total
        context["user_name"] = user_name
        context["form"] = form
        context["rirekilist"] = sql
        context["start_year"] = -settings.START_YEAR
        return context


class ExpenseDetailView(LoginRequiredMixin, generic.DetailView):
    model = Shuuzenhi_expense
    template_name = "shuuzenhi_out/rireki_detail.html"


class ShuuzenhiExpenseListView(LoginRequiredMixin, generic.TemplateView):
    """ 年度別支出データ一覧を表示する """
    model = Shuuzenhi_expense
    # TemplateViewの場合はtemplate_nameは必須．
    template_name = "shuuzenhi_out/expense_list.html"

    def shuuzenhi_expense(self, qs):
        """ 別アプリ（shuuzenhi_in）で呼び出すため、独立した関数とする。
        http://thinkami.hatenablog.com/entry/2015/09/04/235841
        行の集約：values().annotate()の順番で記述する．
        values()：集約キー
        annotate()：下記を参照
        支出合計には修繕費会計への支出分は含めない。2018/03/25
        """
        expenselist = qs.values('year').annotate(
            shuuzen=Sum(Case(When(account_type=2, then='cost'), default=0)),
            kanri=Sum(Case(When(account_type=1, then='cost'), default=0)),
            hoken=Sum(Case(When(account_type=4, then='cost'), default=0)),
            total=F('kanri')+F('shuuzen')
        )
        return expenselist

    def get_context_data(self, **kwargs):
        # はじめに継承元のメソッドを呼び出す．
        context = super().get_context_data(**kwargs)
        # 大規模修繕費を表示すると、全体のバランスが崩れるためmypageのメニューで分ける。
        sw = self.kwargs.get('sw', 0)
        if sw == 1:
            a = Shuuzenhi_expense.objects.select_related().order_by('year')
        else:
            # a = Shuuzenhi_expense.objects.filter(koujitype__lt=20).select_related().order_by('year')
            a = Shuuzenhi_expense.objects.exclude(koujitype=20).select_related().order_by('year')

        context['expenselist'] = self.shuuzenhi_expense(a)
        # aggregateは辞書型を返すようだ。
        # 大規模修繕を外すためにid(20)を決め打ちしている。あまり良く無い！
        if sw == 1:
            context['shuuzen_total'] = Shuuzenhi_expense.objects.filter(
                account_type=2).aggregate(Sum('cost'))['cost__sum']
            context["title"] = "工事支出履歴（大規模修繕含む)"
        else:
            context['shuuzen_total'] = Shuuzenhi_expense.objects.filter(
                account_type=2).filter(
                koujitype__lt=20).aggregate(Sum('cost'))['cost__sum']
            context["title"] = "工事支出履歴（大規模修繕含まず)"

        context['kanri_total'] = Shuuzenhi_expense.objects.filter(
            account_type=1).aggregate(Sum('cost'))['cost__sum']
        context['hoken_total'] = Shuuzenhi_expense.objects.filter(
            account_type=4).aggregate(Sum('cost'))['cost__sum']
        context['all_total'] = context['shuuzen_total']+context['kanri_total']+context['hoken_total']
        context["start_year"] = -settings.START_YEAR
        return context


class KoujiShubetuListView(LoginRequiredMixin, generic.TemplateView):
    """ 修繕工事の工事種別毎の支出一覧 """
    model = Shuuzenhi_expense
    template_name = "shuuzenhi_out/shubetu_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 大規模修繕は除く。
        a = Shuuzenhi_expense.objects.all().exclude(
            koujitype__koujitype='大規模修繕').order_by('koujitype__sequense')
        context['shubetulist'] = a.values(
            'koujitype__koujitype').annotate(total=Sum('cost'))
        return context


class CreateExpenseView(PermissionRequiredMixin, generic.CreateView):
    """ 修繕費支出データを登録する """
    model = Shuuzenhi_expense
    form_class = Shuuzenhi_expenseForm
    template_name = "shuuzenhi_out/rireki_form.html"
    # 必要な権限
    permission_required = ("asset_list.add_assetlist")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('shuuzenhi_out:create')

    def form_valid(self, form):
        messages.success(self.request, "保存しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "保存できませんでした。")
        return super().form_invalid(form)


class CreateKoujiTypeView(PermissionRequiredMixin, generic.CreateView):
    """ 修繕費の工事種別マスターを登録/修正する。
        マスターデータは、数が多くはないので表示しながら入力formを表示させる。
        データが存在すれば表示し、修正か新規登録させる。
        listでページングする場合は https://torina.top/detail/337/#i3 を参照。
    """
    model = Master_koujitype
    form_class = Master_koujitypeForm
    template_name = "shuuzenhi_out/master_koujitype_form.html"
    # 必要な権限
    permission_required = ("admin.add_logentry")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('shuuzenhi_out:create_koujitype')

    def form_valid(self, form):
        """ 上手く保存メッセージを表示できない？ """
        messages.success(self.request, "保存しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "保存できませんでした。")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Master_koujitype.objects.all().order_by('sequense')
        return context


class UpdateKoujitypeView(PermissionRequiredMixin, generic.UpdateView):
    """ 修繕費支出項目マスターを修正する """
    model = Master_koujitype
    form_class = Master_koujitypeForm
    template_name = "shuuzenhi_out/master_koujitype_form.html"
    # 必要な権限
    permission_required = ("admin.add_logentry")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('shuuzenhi_out:create_koujitype')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Master_koujitype.objects.all().order_by('sequense')
        return context


class CreateConstractorView(PermissionRequiredMixin, generic.CreateView):
    """ 施工業者マスターを登録/修正する。
        データが存在すれば表示し、修正か新規登録させる。
        listでページングする場合は https://torina.top/detail/337/#i3 を参照。
    """
    model = Constractor
    form_class = ConstractorForm
    paginate_by = 4
    template_name = "shuuzenhi_out/constractor_form.html"
    # 必要な権限
    permission_required = ("admin.add_logentry")
    # 権限がない場合、Forbidden 403を返す。これがない場合はログイン画面に飛ばす。
    raise_exception = True

    # 保存が成功した場合に遷移するurl
    def get_success_url(self):
        return reverse('shuuzenhi_out:create_constractor')

    def form_valid(self, form):
        messages.success(self.request, "保存しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "保存できませんでした。")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['masterlist'] = Constractor.objects.all().order_by('sequense')
        return context


class UpdateConstractorView(PermissionRequiredMixin, generic.UpdateView):
    """ 施工業者マスターを修正する """
    model = Constractor
    form_class = ConstractorForm

shuuzenhi_out/templates/shuuzenhi_out/constractor_form.html
{# https://stackoverflow.com/questions/39123348/how-to-pass-a-queryset-from-django-to-javascript-function #}
{% extends "base.html" %}

{% block title %}
施工業者の登録
{% endblock title %}

{% block navbar %}
<nav class="navbar is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:master_data' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
<div class="container">
  <br>
  <div class="content has-text-centered">
    <h4>施工業者の登録/修正</h4>
  </div>
  <form method='POST' enctype='multipart/form-data' id='form_style'>
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class='field'>
        <div class='control'>
          <div class='label'>{{ field.label_tag }}</div>
          <div class='my_field'>{{ field }}</div>
          {% if field.help_text %}
            <span class='helptext'>{{ field.help_text }}</span>
          {% endif %}
          {{ field.errors }}
        </div>
      </div>
    {% endfor %}
    {% csrf_token %}
    <br>
    <div class='content has-text-centered my_button'>
      <button type='submit' class='button is-primary'>読込み</button>
      <a class='button is-danger' href='javascript:void(0);' onclick='window.history.back();'>キャンセル</a>
    </div>
  </form>
  {% comment %}
  <form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table is-narrow">
      {{form}}
    </table>
    <div class="content has-text-centered">
      <button type="submit" class="button is-primary ">保存</button>
      <a class="button is-danger" href="javascript:void(0);" onclick="window.history.back();">キャンセル</a>
    </div>
  </form>
  {% endcomment %}
  <hr>
  <table class="table is-narrow is-bordered">
    <thead>
      <tr>
        <th class="has-text-centered">表示順序</th>
        <th class="has-text-centered">業者名</th>
        <th class="has-text-centered">コメント</th>
      </tr>
    </thead>
    <tbody>
      {% for list in masterlist %}
      <tr>
        <td class="has-text-centered">{{ list.sequense }}</td>
        <td class="has-text-left">{{ list.name }}</td>
        <td class="has-text-left">{{ list.comment }}</td>
        <td class="has-text-centered"><a href="{% url 'shuuzenhi_out:update_constractor' list.pk %}">修正</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
</div>
  
{% endblock content %}

shuuzenhi_out/templates/shuuzenhi_out/rireki_list.html
{# https://stackoverflow.com/questions/39123348/how-to-pass-a-queryset-from-django-to-javascript-function #}
{% extends "base.html" %}
{% load humanize %} {# 3桁区切りのため追加 #}
{% load static %} {# {% static  を使うため必要 #}

{% block title %}
個別工事支出
{% endblock title %}

{% block head %}
{# javascriptファイルを取り込む #}
<!--<script src='{% static 'js/moment-with-locales.js' %}'></script>-->
{% endblock head %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'register:mypage' %}">【SG川崎】</a>
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <form class="navbar-item" action="{% url 'shuuzenhi_out:rirekilist'%}" method="get">
        {{form.account_type}}{{form.kouji_type}}{{form.year}}
        <button type="submit" class="button is-primary is-size-7">表示</button>
      </form>

      <a href="{% url 'shuuzenhi_out:shubetulist' %}" class="navbar-item">工事種別合計</a>
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:mypage' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<div class="container is-fluid">
  <br>
  <div class="content has-text-centered">
    <h4>工事リスト</h4>
  </div>
  <div class="content content table-container">
    <table class="table is-narrow">
      <thead>
        <tr class="has-background-grey-lighter">
          <th class="has-text-centered">西暦</th>
          <th class="has-text-centered">期</th>
          <th class="has-text-centered">工事名</th>
          <th class="has-text-centered">工事金額</th>
          <th class="has-text-centered">施工業者</th>
          {#<th class="has-text-centered">見積書ID</th>#}
          {#<th class="has-text-centered">会計区分</th>#}
        </tr>
      </thead>
      <tbody>
        {% for rireki in rirekilist %}
        <tr>
          <td class="has-text-centered">{{ rireki.year }}</td>
          <td class="has-text-centered">{{ rireki.year|add:start_year }}</td>
          {#<td class="has-text-left"><a href="{% url 'shuuzenhi_out:detail' rireki.pk %}">{{ rireki.koujimei|truncatechars:26 }}</a></td>#}
          <td class="has-text-left"><a href="{% url 'shuuzenhi_out:detail' rireki.pk %}">{{rireki.koujimei}}</a></td>
          <td class="has-text-right">{{ rireki.cost|intcomma }}</td>
          <td class="has-text-left">{{ rireki.constractor }}</td>
          {% comment %}
          {% if rireki.quotation_id == 0 %}
            <td class="has-text-right">{{ rireki.quotation_id }}</td>
          {% else %}
            <td class="has-text-right"><a href="{% url 'shuuzenhi_out:view_quotation' rireki.quotation_id %}">{{ rireki.quotation_id }}</a></td>
          {% endif %}
          <td class="has-text-centered">{{ rireki.account_type }}</td>
          {% endcomment %}
        </tr>
        {% endfor %}
        <tr>
          <td></td>
          <!--<td></td>-->
          <td></td>
          <td class="has-text-right">合計</td>
          <td class="has-text-right">{{total|intcomma}}</td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
<br>
</div>
{% endblock content %}

shuuzenhi_out/templates/shuuzenhi_out/rireki_update_list.html
{# https://stackoverflow.com/questions/39123348/how-to-pass-a-queryset-from-django-to-javascript-function #}
{% extends "base.html" %}
{% load humanize %} {# 3桁区切りのため追加 #}

{% block title %}
修繕費支出データの修正
{% endblock title %}

{% block navbar %}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'register:mypage' %}">【SG川崎】</a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <a href="{% url 'register:operate_data' %}" class="navbar-item">戻る</a>
    </div>
  </div>
</nav>
{% endblock navbar %}

{% block content %}
<br>
<div class="container">
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  <div class="content has-text-centered">
    <h4>修繕支出のデータ修正</h4>
  </div>
  <br>
  <div class="content table-container">
    <table class="table is-narrow is-bordered">
      <thead>
        <tr>
          <th class="has-text-centered">西暦</th>
          <th class="has-text-centered">（期）</th>
          <th class="has-text-centered">工事種類</th>
          <th class="has-text-centered">工事名</th>
          <th class="has-text-centered">工事費</th>
          <th class="has-text-centered">施工業者</th>
          <th class="has-text-centered">会計区分</th>
          <th class="has-text-centered">修正</th>
        </tr>
      </thead>
      <tbody>
        {% for list in shuuzenhi_expense_list %}
        <tr>
          <td class="has-text-centered">{{ list.year }}</td>
          <td class="has-text-centered">{{ list.year|add:start_year }}</td>
          <td class="has-text-left">{{ list.koujitype }}</td>
          <td class="has-text-left">{{ list.koujimei }}</td>
          <td class="has-text-right">{{ list.cost|intcomma }}</td>
          <td class="has-text-left">{{ list.constractor }}</td>
          <td class="has-text-left">{{ list.account_type }}</td>
          <td>
            <a href="{% url 'shuuzenhi_out:update' list.id %}" class="button is-primary is-small">
              修正
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {# http://thinkami.hatenablog.com/entry/2016/02/04/231901 #}
  {% include 'page.html' %}
  <br>
</div>
{% endblock content %}