accounting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('asset_list/', include('asset_list.urls', namespace='asset_list')),
    path('kanrihi_in/', include('kanrihi_in.urls', namespace='kanrihi_in')),
    path('kanrihi_out/', include('kanrihi_out.urls', namespace='kanrihi_out')),
    path('shuuzenhi_in/', include(
        'shuuzenhi_in.urls', namespace='shuuzenhi_in')),
    path('shuuzenhi_out/', include(
        'shuuzenhi_out.urls', namespace='shuuzenhi_out')),
    path('parking_in/', include('parking_in.urls', namespace='parking_in')),
    path('parking_out/', include('parking_out.urls', namespace='parking_out')),
    path('balance/', include('balance.urls', namespace='balance')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asset_list/urls.py
from django.urls import path
from asset_list import views

app_name = 'asset_list'
urlpatterns = [
    # データ表示
    path('assetlist/', views.AssetListView.as_view(), name='assetlist'),
    path('balance_sheet/', views.BalanceSheetView.as_view(), name='balance_sheet'),
    # データ登録
    path('create/', views.CreateAssetView.as_view(), name='create'),
    path('create_master',
         views.CreateMasterView.as_view(), name='create_master'),
    # 修正のための一覧表示
    path('update_list/',
         views.UpdateAssetlistView.as_view(), name='update_list'),
    # データ修正
    path('update/<int:pk>/', views.UpdateAssetView.as_view(), name='update'),
    path('update_master/<int:pk>/',
         views.UpdateMasterView.as_view(), name='update_master'),
    # CSVデータExport
    path('export/', views.asset_export, name='export'),

]

balance/urls.py
from django.urls import path

from balance import views

app_name = 'balance'
urlpatterns = [
    # データ表示
    path('shuuzenhi/', views.ShuuzenhiBalanceView.as_view(), name='shuuzenhi'),
    path('check_shuuzenhi/', views.CheckShuuzenhiBalanceView.as_view(), name='check_shuuzenhi'),
    path('kanrihi/', views.KanrihiBalanceView.as_view(), name='kanrihi'),
    path('check_kanrihi/', views.CheckKanrihiBalanceView.as_view(), name='check_kanrihi'),
]

kanrihi_in/urls.py
from django.urls import path
from kanrihi_in import views

app_name = 'kanrihi_in'
urlpatterns = [
    # データ表示
    path('incomelist/',
         views.IncomeListView.as_view(), name='incomelist'),
    path('uchiwakelist/',
         views.UchiwakeListView.as_view(), name='uchiwakelist'),
    # データ登録
    path('create_income',
         views.CreateIncomeView.as_view(), name='create_income'),
    path('create_master',
         views.CreateMasterView.as_view(), name='create_master'),
    # 修正のための一覧表
    path('update_list/',
         views.UpdateIncomelistView.as_view(), name='update_list'),
    path('update/<int:pk>/',
         views.UpdateIncomeView.as_view(), name='update'),
    path('update_master/<int:pk>/',
         views.UpdateMasterView.as_view(), name='update_master'),
    path('create_category',
         views.CreateCategoryView.as_view(), name='create_category'),
    path('update_category/<int:pk>/',
         views.UpdateCategoryView.as_view(), name='update_category'),
#    # CSVデータExport
#    path('export/', views.kanrihi_in_export, name='export'),
]

kanrihi_out/urls.py
from django.urls import path

from kanrihi_out import views

app_name = 'kanrihi_out'
urlpatterns = [
    # データ表示
    path('expenselist/',views.KanrihiExpenseListView.as_view(), name='expenselist'),
    path('expensechklist/',views.KanrihiExpenseCheckListView.as_view(), name='expensechklist'),
    path('breakdownlist/',views.BreakdownListView.as_view(), name='breakdownlist'),
    # データの登録／修正
    path('create_expense',views.CreateExpenseView.as_view(), name='create_expense'),
    path('update_list/',views.UpdateExpenselistView.as_view(), name='update_list'),
    path('update/<int:pk>/',views.UpdateExpenseView.as_view(), name='update'),
    path('create_master',views.CreateMasterView.as_view(), name='create_master'),
    path('update_master/<int:pk>/',views.UpdateMasterView.as_view(), name='update_master'),
    path('create_category',views.CreateCategoryView.as_view(), name='create_category'),
    path('update_category/<int:pk>/',views.UpdateCategoryView.as_view(), name='update_category'),
#    # CSVデータExport
#    path('export/', views.kanrihi_out_export, name='export'),
]

parking_out/urls.py
from django.urls import path

from parking_out import views

app_name = 'parking_out'
urlpatterns = [
    # データ表示
    path('expendlist/', views.ExpenditureListView.as_view(), name='expendlist'),
    # データ登録
    path('create', views.ExpenditureCreateView.as_view(), name='create'),
    # データ修正
    path('update_list/', views.UpdateListView.as_view(), name='update_list'),
    path('update/<int:pk>/', views.UpdateExpenditureView.as_view(), name='update'),
]

register/urls.py
from django.urls import path
from register.views import (MypageView, OperateDataView, MasterDataView,
                            OperateRepairDataView, Login, Logout)


"""
https://torina.top/detail/222/
"""
app_name = 'register'
urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('mypage', MypageView.as_view(), name='mypage'),
    path('operate_data/', OperateDataView.as_view(), name='operate_data'),
    path('operate_repair_data/', OperateRepairDataView.as_view(),
         name='operate_repair_data'),
    path('master_data/', MasterDataView.as_view(), name='master_data'),
]

register/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

register/forms.py
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'
            field.widget.attrs['placeholder'] = field.label

register/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from .forms import LoginForm


class MypageView(LoginRequiredMixin, TemplateView):
    template_name = "register/mypage.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['user_id'] = self.request.user.id
        return context


class OperateDataView(LoginRequiredMixin, TemplateView):
    template_name = "register/operate_data.html"


class OperateRepairDataView(LoginRequiredMixin, TemplateView):
    template_name = "register/operate_repair_data.html"


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'register/logout.html'


class MasterDataView(LoginRequiredMixin, TemplateView):
    template_name = "register/master_data.html"

register/templates/register/login.html
{% extends "base.html" %}
{% block navbar %}
{# https://bulma.io/documentation/components/navbar/ #}
<nav class="navbar navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
</nav>
{% endblock navbar %}

{% block content %}
<div class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">ログインページ</h1>
      <h2 class="subtitle">Ver-{{VERSION_NO}}</h2>
    </div>
  </div>
 </div>
<div class="container is-fluid ">
  <br>
  <div class="content">
    <form method='POST' enctype='multipart/form-data' id='form_style'>
      {{ form.non_field_errors }}
      {% for field in form %}
        <div class='field'>
          <div class='control'>
            <div class='label'>{{ field.label_tag }}</div>
            <div class='my_field'>{{ field }}</div>
            {% if field.help_text %}
              <span class='helptext'>{{ field.help_text }}</span>
            {% endif %}
            {{ field.errors }}
          </div>
        </div>
      {% endfor %}
      {% csrf_token %}
      <br>
      <div class='my_button has-text-centered'>
        <button type='submit' class='button is-primary'>ログイン</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

register/templates/register/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="content has-text-centered">
  <h3>ログアウトしました</h3>
  <a class="button is-primary" href="{% url 'register:mypage' %}" >再ログイン<a>
</div>
{% endblock %}

register/templates/register/master_data.html
{% extends "base.html" %}
{% block title %}
管理者ページ
{% endblock title %}
{% block navbar %}
{# https://bulma.io/documentation/components/navbar/ #}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">資産データ</a>
        <div class="navbar-dropdown">
          <a href="{% url 'asset_list:create_master' %}" class="dropdown-item">資産マスターの登録/修正<a>
        </div>
      </div>
        <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">管理費会計データ</a>
        <div class="navbar-dropdown">
          <a href="{% url 'kanrihi_in:create_master' %}" class="dropdown-item">収入項目の登録/修正<a>
          <a href="{% url 'kanrihi_out:create_master' %}" class="dropdown-item">支出項目の登録/修正<a>
          <hr class="navbar-divider">
          <a href="{% url 'kanrihi_in:create_category' %}" class="dropdown-item">収入カテゴリーの登録/修正<a>
          <a href="{% url 'kanrihi_out:create_category' %}" class="dropdown-item">支出カテゴリーの登録/修正<a>
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">修繕費会計データ</a>
        <div class="navbar-dropdown">
          <a href="{% url 'shuuzenhi_in:create_master' %}" class="dropdown-item">修繕費収入項目の登録<a>
          <a href="{% url 'shuuzenhi_out:create_koujitype' %}" class="dropdown-item">修繕工事タイプの登録/修正<a>
          <a href="{% url 'shuuzenhi_out:create_constractor' %}" class="dropdown-item">施工業者の登録/修正<a>
        </div>
      </div>

    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <a class="button is-light is-size-7 has-text-weight-bold" href="{% url 'register:mypage' %}" >戻る</a>
      </div>
    </div>
  </div>
</nav>
{% endblock navbar %}
{% block content %}
<br>
<div class="content has-text-centered ">
  <h2>マスターデータの登録／修正</h2>
</div>
{% endblock %}

register/templates/register/mypage.html
{% extends "base.html" %}
{# http://cccabinet.jpn.org/bootstrap4/components/navbar #}
{% block title %}
SG川崎 会計
{% endblock %}

{% block navbar %}
{# https://bulma.io/documentation/components/navbar/ #}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">財産目録</a>
        <div class="navbar-dropdown">
          <a href="{% url 'asset_list:assetlist' %}" class="navbar-item">財産目録<a>
          <a href="{% url 'asset_list:balance_sheet' %}" class="navbar-item">貸借対照表<a>
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">管理会計</a>
        <div class="navbar-dropdown">
          <a href="{% url 'balance:kanrihi' %}" class="dropdown-item">収支一覧（議案書）<a>
          {% if perms.asset_list.add_assetlist %}
            <a href="{% url 'balance:check_kanrihi' %}" class="dropdown-item">収支一覧（計算）<a>
          {% endif %}
          <hr class="navbar-divider">
          <a href="{% url 'kanrihi_in:incomelist' %}" class="dropdown-item">収入履歴</a>
          <a href="{% url 'kanrihi_in:uchiwakelist' %}" class="dropdown-item">その他収入</a>
          <hr class="navbar-divider">
          <a href="{% url 'kanrihi_out:expenselist' %}" class="dropdown-item">支出履歴<a>
          {% if perms.asset_list.add_assetlist %}
            <a href="{% url 'kanrihi_out:expensechklist' %}" class="dropdown-item">支出履歴(小規模修繕)<a>
          {% endif %}
          <a href="{% url 'kanrihi_out:breakdownlist' %}" class="dropdown-item">支出内訳<a>
          <hr class="navbar-divider">
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">修繕会計</a>
        <div class="navbar-dropdown">
          <a href="{% url 'balance:shuuzenhi' %}" class="dropdown-item">収支一覧（議案書）<a>
          {% if perms.asset_list.add_assetlist %}
            <a href="{% url 'balance:check_shuuzenhi' %}" class="dropdown-item">収支一覧（計算）<a>
          {% endif %}
          <hr class="navbar-divider">
          <a href="{% url 'shuuzenhi_in:incomelist' %}" class="dropdown-item">収入履歴<a>
          <a href="{% url 'shuuzenhi_in:uchiwakelist' %}" class="dropdown-item">その他収入</a>
          <hr class="navbar-divider">
          <a href="{% url 'shuuzenhi_out:expenselist' %}" class="dropdown-item">支出履歴<a>
          <a href="{% url 'shuuzenhi_out:expenselist' '1' %}" class="dropdown-item">支出履歴(大規模修繕含む)<a>
          <hr class="navbar-divider">
          <a href="{% url 'shuuzenhi_out:rirekilist' %}" class="dropdown-item">個別工事支出<a>
          {% comment %} <a href="{% url 'shuuzenhi_out:quotation' %}" class="dropdown-item">見積書<a>  {% endcomment %}
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">駐車場会計</a>
        <div class="navbar-dropdown">
          <a href="{% url 'parking_in:incomelist' %}" class="dropdown-item">収入履歴<a>
          <a href="{% url 'parking_out:expendlist' %}" class="dropdown-item">支出履歴<a>
        </div>
      </div>
    </div>
    <div class="navbar-end">
      {% if perms.asset_list.add_assetlist %}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">管理者メニュー</a>
          <div class="navbar-dropdown">
            <a href="{% url 'register:operate_data' %}" class="navbar-item ">決算データ入力</a>
            <a href="{% url 'register:master_data' %}" class="navbar-item ">マスターデータ</a>
          </div>
        </div>

      {% endif %}
      <div class="navbar-item">
        <a class="button is-light is-size-7 has-text-weight-bold" href="{% url 'register:logout' %}" >ログアウト</a>
      </div>
    </div>
  </div>
</nav>
{% endblock navbar %}
<br>
{% block content %}
<div class="content has-text-centered">
  <br>
  <h4>マンション会計履歴</h4>
  <br>
  {% load static%}
  <img src="{% static 'ramune.png' %}" style="max-height:500px" class="img-fluid" />
</div>
{% endblock %}

register/templates/register/operate_data.html
{% extends "base.html" %}
{% block title %}
管理者ページ
{% endblock title %}
{% block navbar %}
{# https://bulma.io/documentation/components/navbar/ #}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">資産データ</a>
        <div class="navbar-dropdown">
          <a href="{% url 'asset_list:create' %}" class="dropdown-item">資産データの登録<a>
          <hr class="navbar-divider">
          <a href="{% url 'asset_list:update_list' %}" class="dropdown-item">資産データの修正<a>
        </div>
      </div>
        <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">管理費会計データ</a>
        <div class="navbar-dropdown">
          <a href="{% url 'kanrihi_in:create_income' %}" class="dropdown-item">管理費収入データの登録<a>
          <a href="{% url 'kanrihi_out:create_expense' %}" class="dropdown-item">管理費支出データの登録<a>
          <hr class="navbar-divider">
          <a href="{% url 'kanrihi_in:update_list' %}" class="dropdown-item">管理費収入データの修正<a>
          <a href="{% url 'kanrihi_out:update_list' %}" class="dropdown-item">管理費支出データの修正<a>
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">修繕費会計データ</a>
        <div class="navbar-dropdown">
          <a href="{% url 'shuuzenhi_in:create' %}" class="dropdown-item">修繕費収入データの登録<a>
          <a href="{% url 'shuuzenhi_out:create' %}" class="dropdown-item">修繕費支出データの登録<a>
          <hr class="navbar-divider">
          <a href="{% url 'shuuzenhi_in:update_list' %}" class="dropdown-item">修繕費収入データの修正<a>
          <a href="{% url 'shuuzenhi_out:update_list' %}" class="dropdown-item">修繕費支出データの修正<a>
          {#<a href="{% url 'shuuzenhi_out:export' %}" class="dropdown-item">修繕費支出データCSV<a>#}
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">駐車場会計データ</a>
        <div class="navbar-dropdown">
          <a href="{% url 'parking_in:create' %}" class="dropdown-item">駐車場収入データの登録<a>
          <a href="{% url 'parking_out:create' %}" class="dropdown-item">駐車場使用料支出データの登録<a>
          <hr class="navbar-divider">
          <a href="{% url 'parking_in:update_list' %}" class="dropdown-item">駐車場収入データの修正<a>
          <a href="{% url 'parking_out:update_list' %}" class="dropdown-item">駐車場使用料支出データの修正<a>
        </div>
      </div>

    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <a class="button is-light is-size-7 has-text-weight-bold" href="{% url 'register:mypage' %}" >戻る</a>
      </div>
    </div>
  </div>
</nav>
{% endblock navbar %}
{% block content %}
<br>
<div class="content has-text-centered ">
  <h2>会計データの登録／修正</h2>
</div>
{% endblock %}

register/templates/register/operate_repair_data.html
{% extends "base.html" %}
{% block title %}
管理者ページ
{% endblock title %}
{% block navbar %}
{# https://bulma.io/documentation/components/navbar/ #}
<nav class="navbar is-fixed-top is-black is-size-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">【SG川崎】</a>
    {# ハンバーガアイコンのため以下の5行とbase.htmlでのjsスクリプトが必要 #}
    <a role="button" class="navbar-burger " aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">修繕計画データ</a>
        <div class="navbar-dropdown">
          <a href="{% url 'repair_plan:add_repair_plan' %}" class="dropdown-item">修繕計画データの登録<a>
          <a class="dropdown-item" href="{% url 'repair_plan:update_repair_plan_list' %}">修繕計画データ修正</a>
          {% if user.is_staff %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'repair_plan:import_repair_plan' %}">修繕計画データ読込み</a>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <a class="button is-light is-small" href="{% url 'repair_plan:repair_work' %}" >戻る</a>
      </div>
    </div>
  </div>
</nav>
{% endblock navbar %}
{% block content %}
<br>
<div class="content has-text-centered ">
  <h4>修繕工事データの登録／修正</h4>
</div>
{% endblock %}